version: "3"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:3.6.2-jessie
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
