// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!

export const loader: string;
export const error: string;
export const header: string;
export const footer: string;
export const container: string;
export const questionCard: string;
export const questionTop: string;
export const qNumber: string;
export const correctAnswer: string;
export const correctText: string;
