// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!

export const successBanner: string;
export const container: string;
export const createButton: string;
export const formCard: string;
export const firstRow: string;
export const formName: string;
export const secondRow: string;
export const publishedBadge: string;
export const unpublishedBadge: string;
export const loader: string;
export const error: string;
