// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!

export const container: string;
export const getStarted: string;
export const examplesContainer: string;
export const cardsContainer: string;
export const exampleCard: string;
