// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!

export const trueFalse: string;
export const multipleChoice: string;
export const matching: string;
export const columnContainer: string;
export const column: string;
export const letter: string;
export const row: string;
