// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!

export const addButton: string;
export const removeButton: string;
export const row: string;
export const listInput: string;
