// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!

export const container: string;
export const header: string;
export const headerButton: string;
export const select: string;
export const nameInput: string;
export const questionCard: string;
export const questionTop: string;
export const centeredBadge: string;
export const optionsPrompt: string;
export const answerPrompt: string;
export const columnContainer: string;
export const column: string;
