// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!

export const container: string;
export const error: string;
export const success: string;
export const inputs: string;
